// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5lCjVOzk4rvz-gOU0rIIK4QibTO6ekRY',
    appId: '1:601731908423:web:bc180f55fc58cdd07dc262',
    messagingSenderId: '601731908423',
    projectId: 'desiredwash-42237',
    authDomain: 'desiredwash-42237.firebaseapp.com',
    storageBucket: 'desiredwash-42237.firebasestorage.app',
    measurementId: 'G-F8W6P6XPYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2tdxgbyX17drpST35n4X-07qlHehY8yk',
    appId: '1:601731908423:android:7fdeb0d8668673c77dc262',
    messagingSenderId: '601731908423',
    projectId: 'desiredwash-42237',
    storageBucket: 'desiredwash-42237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWBsZHRduX3rqSoV1ZdUEAipZKHYOQ9-Q',
    appId: '1:601731908423:ios:4c360cf3e6f2b88d7dc262',
    messagingSenderId: '601731908423',
    projectId: 'desiredwash-42237',
    storageBucket: 'desiredwash-42237.firebasestorage.app',
    androidClientId: '601731908423-3qkc0fh9ogafm6ua2vq1s78bmg761jjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.desiredWash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWBsZHRduX3rqSoV1ZdUEAipZKHYOQ9-Q',
    appId: '1:601731908423:ios:4c360cf3e6f2b88d7dc262',
    messagingSenderId: '601731908423',
    projectId: 'desiredwash-42237',
    storageBucket: 'desiredwash-42237.firebasestorage.app',
    androidClientId: '601731908423-3qkc0fh9ogafm6ua2vq1s78bmg761jjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.desiredWash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5lCjVOzk4rvz-gOU0rIIK4QibTO6ekRY',
    appId: '1:601731908423:web:6b854c17cb802c547dc262',
    messagingSenderId: '601731908423',
    projectId: 'desiredwash-42237',
    authDomain: 'desiredwash-42237.firebaseapp.com',
    storageBucket: 'desiredwash-42237.firebasestorage.app',
    measurementId: 'G-565VZ7QP7M',
  );
}
